name: axie-studio-backend
region: nyc1

services:
- name: backend-api
  source_dir: /
  github:
    repo: OGGsd/agent-platform
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  
  envs:
  # Langflow Connection
  - key: LANGFLOW_URL
    scope: RUN_TIME
    value: "https://langflow-tv34o.ondigitalocean.app"
  
  # Security
  - key: SECRET_KEY
    scope: RUN_TIME
    value: "axie-studio-secret-key-2024-production"
  - key: JWT_SECRET
    scope: RUN_TIME
    value: "axie-studio-jwt-secret-2024-production"
  
  # CORS Configuration
  - key: ALLOWED_ORIGINS
    scope: RUN_TIME
    value: "https://axie-studio-frontend-niv3muiya-swdgs-projects.vercel.app,https://axiestudio.vercel.app,https://axiestudio.com,https://*.axiestudio.com"
  
  # Admin Configuration
  - key: ADMIN_EMAIL
    scope: RUN_TIME
    value: "stefan@axiestudio.se"
  - key: ADMIN_PASSWORD
    scope: RUN_TIME
    value: "AxieStudio2024!"
  
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
  
  routes:
  - path: /api
  - path: /health

domains:
- domain: axie-studio-backend.ondigitalocean.app
  type: PRIMARY
